create role anon; create role authenticated; create role service_role bypassrls;
create schema extensions;
create table public.users(id uuid primary key default gen_random_uuid(),name text not null,pin_hash text not null,role text not null default 'user',active boolean not null default true,created_at timestamptz not null default now());
create table public.locations(id uuid primary key default gen_random_uuid(),name text not null,type text not null check(type in ('cantiere','magazzino')),active boolean not null default true,notes text not null default '',created_at timestamptz not null default now());
create table public.articles(id uuid primary key default gen_random_uuid(),name text not null,category text not null default '',internal_code text not null default '',serial text not null default '',active boolean not null default true,location_id uuid references locations(id),state text not null default 'home' check(state in ('home','in_carico')),current_holder_user_id uuid references users(id),last_known_user_id uuid references users(id),last_movement_at timestamptz,last_note text not null default '',created_at timestamptz not null default now());
create table public.movements(id uuid primary key default gen_random_uuid(),article_id uuid references articles(id),article_name text not null,article_serial text not null default '',movement_type text not null check(movement_type in ('prelievo','restituzione','passaggio','trasferimento')),from_location_id uuid references locations(id),to_location_id uuid references locations(id),from_user_id uuid references users(id),to_user_id uuid references users(id),recorded_by_user_id uuid references users(id),note text not null default '',image_data text,session_id text not null default '',created_at timestamptz not null default now(),geo_lat float8,geo_lng float8,geo_accuracy_m float8,geo_captured_at timestamptz,geo_source text,geo_address text);
insert into public.users(id,name,pin_hash,role) values ('00000000-0000-4000-8000-000000000001','Manager','legacy','admin'),('00000000-0000-4000-8000-000000000002','Worker','legacy','user'),('00000000-0000-4000-8000-000000000003','Other','legacy','user');
insert into public.locations(id,name,type) values('00000000-0000-4000-8000-000000000010','Warehouse','magazzino'),('00000000-0000-4000-8000-000000000011','Site','cantiere');
insert into public.articles(id,name,location_id) values('00000000-0000-4000-8000-000000000020','Test tool','00000000-0000-4000-8000-000000000010');
